### ISSUE TITLE
Add support for DateTime.Add(Duration) and DateTimeOffset.Add(Duration)

### ISSUE THREAD

**Issue by preeder** [thomaslevesque/Iso8601DurationHelper#2]
Implementing operator+ is great, but people who have worked a lot with adding TimeSpan  values to DateTime values, .Add(TimeSpan) is very common.  Having .Add(Duration) extension methods for both DateTime and DateTimeOffset is intuitive.

**Comment by thomaslevesque** [comment]
Hi @preeder,

Great suggestion, thanks!
Would you be interested in sending a PR for this?

**Comment by preeder** [comment]
Writing it now
